### ISSUE TITLE
Minimizing a note is choppy

### ISSUE THREAD

**Issue by julmot** [txusko/PostItAll#30]
**Expected**
Smooth animation when minimizing a note.

**Actual behavior**
The animation feels a bit laggy as it jumps to the top edge, then to the bottom. After opening it again it jumps to the previous position very choppy.

**Example**
![minify](https://cloud.githubusercontent.com/assets/8310677/13738587/4bf6a666-e9c6-11e5-81b3-9ccb6e06c10b.gif)
[noteTest.zip](https://github.com/txusko/PostItAll/files/171571/noteTest.zip)
(just click inside the read area and minimize the note)

**Environment**
Firefox 47.0a2

**Comment by txusko** [comment]
Yes, this is something I was trying to fix some months ago without success. 
I can't remember where the problem was, but it was something relative to the jquery animate() function and the change of the "position" css attribute *. 
I can remeber that when the animation was smooth with Firefox, it wasn't with Chrome, and viceversa.

I will try to improve the method, but I can't assure a solution.

* You can check it in the restoreOldPosition method

**Comment by julmot** [comment]
I think instead of animation the `position` property it would be better to use `transform` as this triggers hardware acceleration which is very important on mobile devices.

**Comment by txusko** [comment]
Ok, I will investigate.

**Comment by txusko** [comment]
I hope it works fine now ...
https://github.com/txusko/PostItAll/commit/49cb6c3d33c2019f8e4f4ac8e8bfcad861c44cde
