### ISSUE TITLE
Suspected bug

### ISSUE THREAD

**Issue by roghellman** [txusko/PostItAll#37]
It could be how I am using this, but it does appear that ~line 982 of jquery.postitall.js that reads:
var $el = element;
should instead read:   var $el= $(element);

I would also like to see a new feature.  Being able to apply the name of the note creator at the bottom of the note.  Possibly the date of creation as well.  Formatted to look like a footnote.

**Comment by txusko** [comment]
Hi @roghellman,
the method works fine, this change from the original source is because in this plugin you can attach a note defining the class selector ('#idSelector') or by passing the jquery element ( $('#idSelector') ).

```javascript
$.PostItAll.new({
        attachedTo : {
        element : '#idSelector'
    }
});
$.PostItAll.new({
        attachedTo : {
        element : $('#idSelector')
    }
});
```
I hope it helps.

About the new feature you are talking about, I'm so sorry but I'm currently do not have time to work anymore on this plugin. If this situation changes I will try to include it in a release (or try to do something). Anyway, you can add metadata to the note (a specific field for the creator) and acces it by the info icon in the bottom of the note, not the same but ...

Best Regards
Javi Filella
